### PR TITLE
Export SingleCellExperiment and SummarizedExperiment

### PR DESCRIPTION
**Pull request by fionarhuang**
The corresponding work is updated in the branch exportSE_fiona.
To summarize the work, I have created the singleCellExperiment (sce) and SummarizedExperiment  (se) in the following way:

**The original output from the prepare_results_for_shiny.R is as below.**
list(wideResults = list(edgeR = edgeRwide), 
             longResults = list(edgeR = edgeRlong), 
             geneModels = genemodels,
             bwFiles = bwfiles, 
             bwCond = condition, 
             dimReds = list(MDS = mds),
             abundances = list(logCPM = logcpms), 
             geneInfo = genes)

I have created the sce and se to store the result as below.
Assays: 
a list of two tables: 
raw count (data saved from run_dge_edge.R)
count in logCPM (apply cpm to the raw count with log =TRUE and prior.count = 2; actually, it is the matrix form of value column in abundances)

colData: cbind(bwFiles,  bwCond)

rowData: 
Gene, symbol, gene_biotype, chromosome, strand
These columns are from tx2gene and the row orders are the same to the rownames of the count table (data saved from run_dge_edge.R)
type, group
These columns are obtained from mds
Output from edgeR
The result table of each contrast is saved as a column in the rowData with the name of the contrast. So, actually, it's a DataFrame in a column.

Metadata: list(geneModels, geneInfo)

ReducedDims: (only exists in sce)
Mds without ID type and group columns

### CODE REVIEW

**Comment by csoneson** [comment]
This is great! A couple of things:
- we should make sure that this works together with Stephany's `tximeta` changes (where the data should already exist in a `SummarizedExperiment` for example). Maybe you could try to merge the `stephany_gencodeEdit` branch into this one and adapt the generation of the `SummarizedExperiment` objects accordingly.
- I don't think we actually need the `SummarizedExperiment`. The `SingleCellExperiment` should work just as well, since it extends `SummarizedExperiment`. If you don't need the reduced dim, you just ignore it. 
- All sample annotations should go in `colData` (also `group`, `type`, any other columns that exist in the original `metadata` table).

**Comment by fionarhuang** [comment]
1. Could we merge the stephany_gencodeEdit branch to the main branch if it's already done? And then, I could do the corresponding update. I am kind of worry it would lead to some merge conflicts later or I could do the update after stephany's branch.
2. I could simply delete the SummarizedExperiment object. I create it just in case someone have issues with the installation of the singleCellExperiment package. I am not sure whether it's a mature R package...
3. Sorry, I probably forgot to mention it. group and type are already in colData. I will add the columns that exist in the original _metadata_ table

**Comment by csoneson** [comment]
1. I think that would lead to the same kind of merge conflicts - either you get them when you merge the `gencode` branch or when you merge the `master` branch :) maybe @sorjuela has some input here, I guess the branch is mostly done but still waiting for a few updates to `tximeta`. The main point was just to develop the `SE` stuff with those changes in mind. 
2. I think `SingleCellExperiment` should be mature enough by now. It's in the release branch of Bioconductor, so I'd say it's fine. 
3. Ok, great :)

**Comment by sorjuela** [comment]
Hi, so Fiona and I talked and might be better to not change/merge this until the `tximeta` updates. Then maybe she can merge to my branch, or we can think of something easier ;)

**Pull request merged**
